Allow people to opt out of starting mongodb
codeship/scripts pull request #115
Opened 2016-09-27 16:02 UTC by steve-ross

In some cases you may just need the MongoDB tools, this update allows users to set an environment variable to disable starting mongo: ie: $MONGODB_START=N (or anything but the default: "Y") will cause the script to not actually start MongoDB

2016-09-27 16:07 UTC, mlocher requested changes
Thanks for submitting the PR, I just have a minor comment regarding indentation, otherwise 👍

2016-09-27 16:07 UTC, mlocher commented on packages/mongodb.sh
> +	sleep "${MONGODB_WAIT_TIME}"
Indentation for the two shell commands seems to be off

2016-09-27 16:09 UTC, steve-ross commented on packages/mongodb.sh
> +	sleep "${MONGODB_WAIT_TIME}"
Ah sorry edited directly on github  :/

2016-09-27 16:18 UTC, steve-ross commented on packages/mongodb.sh
> +	sleep "${MONGODB_WAIT_TIME}"
@mlocher soft tabs (2 spaces) ok?

2016-09-28 08:14 UTC, mlocher approved these changes

2016-09-28 08:15 UTC, merged

2016-09-28 08:15 UTC, mlocher commented
Thanks for the PR Steve :)