Tomcat install script
codeship/scripts pull request #124
Opened 2016-12-13 16:18 UTC by BoVice

2016-12-13 16:25 UTC, mlocher requested changes
Great to get this added, I left a couple comments to streamline the script a bit.

2016-12-13 16:25 UTC, mlocher commented on packages/tomcat.sh
> +TOMCAT_DIR=${TOMCAT_DIR="$HOME/tocat"}
typo with the `TOMCAT_DIR`

2016-12-13 16:25 UTC, mlocher commented on packages/tomcat.sh
> +tar -xaf "${CACHED_DOWNLOAD}" --directory "${TOMCAT_DIR}"
Could you add `--strip-components=1`, which will extract the contents directly to `TOMCAT_DIR` and not to a subdirectory called `apache-tomcat-${TOMCAT_VERSION}`

2016-12-13 16:25 UTC, mlocher commented on packages/tomcat.sh
> +bash ${TOMCAT_DIR}/bash apache-tomcat-${TOMCAT_VERSION}/bin/startup.sh
With the changes to the `tar` command above, we can simplify this command.

2016-12-13 16:25 UTC, mlocher commented on packages/tomcat.sh
> +cd -
As we're not `cd`'ing to a different directory, we don't need to switch back and can remove this command.

2016-12-13 16:27 UTC, mlocher commented
Please also add a test installation to the `test.sh` script, so we can make sure the script works as expected.

2016-12-13 16:31 UTC, mlocher commented on packages/tomcat.sh
> +wget --continue --output-document "${CACHED_DOWNLOAD}" "http://www-us.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz"
I just noticed, that the URL includes the major version on the directory level as well. An example of how to parse the major version from a variable is available at https://github.com/codeship/scripts/blob/master/packages/elasticsearch.sh#L19

2016-12-13 16:34 UTC, BoVice commented on packages/tomcat.sh
> +cd -
i screwed this part up when before i push the last commit. Just changed it back to what I originally had.

2016-12-14 00:00 UTC, VanTanev commented on packages/tomcat.sh
> +bash tomcat/bin/version.sh | grep "Apache Tomcat/${TOMCAT_VERSION}"
@BoVice Shouldn't this be `bash ${TOMCAT_DIR}/bin/version.sh | grep "Apache Tomcat/${TOMCAT_VERSION}"` ?

2016-12-14 18:46 UTC, jasonsouza commented on packages/tomcat.sh
> +bash tomcat/bin/version.sh | grep "Apache Tomcat/${TOMCAT_VERSION}"
Thanks for the catch! @VanTanev

2016-12-15 00:00 UTC, VanTanev commented
@BoVice while this is not yet merged:

I found myself needing to start tomcat with catalina instead of the normal server startup, ie:
 - Setup tomcat (don't start)
 - Attach tomcat webapps
 - Start with `${TOMCAT_DIR}/bin/catalina.sh run`

To that effect, it might be useful to have an env var like 
```bash
TOMCAT_AUTOSTART=${TOMCAT_AUTOSTART:="1"}
```

and do 
```bash
if [ "$TOMCAT_AUTOSTART" -eq "1" ]; then
  # Make sure to use the exact parameters you want for Tomcat and give it enough sleep time to properly start up
  bash ${TOMCAT_DIR}/bin/startup.sh
  sleep ${TOMCAT_WAIT_TIME}
fi
```

2016-12-22 15:06 UTC, BoVice commented
Thanks for another great suggestion @VanTanev. Added to the script 😄 Sorry for the delay in revisiting this script.

2016-12-22 15:07 UTC, mlocher approved these changes
:shipit: if the build is green

2016-12-22 15:24 UTC, merged