Install script for custom geckodriver versions
codeship/scripts pull request #182
Opened 2017-06-09 17:02 UTC by joesiewert

2017-06-09 17:07 UTC, mlocher requested changes
Love the bats tests, can you make sure we call bats tests for packages on the build? Maybe in a separate pipeline?

Other than that only 2 smaller issues, which I'd like to get some feedback on.

2017-06-09 17:07 UTC, mlocher commented on tests/packages/geckodriver.bats
> +  mkdir -p "${HOME}/cache"
Why do we need to create the cache directory here, and if we need, I'd add this to the `setup` function.

2017-06-09 17:07 UTC, mlocher commented on tests/packages/geckodriver.bats
> +  export GECKODRIVER_VERSION="0.16.1"
I would add a command to clear out the cached download, so we always install from the upstream provider and get notified if they change a URL or something similar.

2017-06-09 17:33 UTC, joesiewert commented on tests/packages/geckodriver.bats
> +  export GECKODRIVER_VERSION="0.16.1"
Don't we already clear the entire cache during setup in `tests/setup.sh`?

2017-06-09 17:54 UTC, mlocher commented on tests/packages/geckodriver.bats
> +  export GECKODRIVER_VERSION="0.16.1"
Yeah, I wanted to get rid of that, once we have all tests converted to bats though, and have each test take care of whether it wants to use the cache or not. 

I started to add that to all other bats files, e.g. https://github.com/codeship/scripts/blob/master/tests/cache/bower.bats#L4

2017-06-13 07:43 UTC, mlocher approved these changes
:shipit:

2017-06-13 14:50 UTC, merged