Add redis deployment
codeship/scripts pull request #194
Opened 2017-11-11 14:23 UTC by acasajus

Download, compile and run redis

2017-11-11 19:09 UTC, joesiewert requested changes
Thanks for the PR - just a few small changes

2017-11-11 19:09 UTC, joesiewert commented on deployments/redis.sh
> +# \curl -sSL https://raw.githubusercontent.com/codeship/scripts/master/packages/cockroachdb.sh | bash -s
`cockroachdb.sh` > `redis.sh`

2017-11-11 19:09 UTC, joesiewert commented on deployments/redis.sh
> +# Make sure to use the exact parameters you want for DynamoDB and give it enough sleep time to properly start up
Remove or update this comment

2017-11-11 19:09 UTC, joesiewert commented on deployments/redis.sh
> +REDIS_PORT=${REDIS_PORT:="26257"}
`26257` > `6380`

Default Redis port is 6379, but will be in use by the older Redis version already running

2017-11-11 19:09 UTC, joesiewert commented on deployments/redis.sh
> +# \curl -sSL https://raw.githubusercontent.com/codeship/scripts/master/packages/cockroachdb.sh | bash -s
Move script from `deployments/redis.sh` to `packages/redis.sh`

2017-11-13 12:09 UTC, acasajus commented
Clearly I copied the script from the cockroachdb one 😃

2017-11-14 00:37 UTC, joesiewert approved these changes

2017-11-14 00:37 UTC, joesiewert commented
🙇

2017-11-14 00:37 UTC, merged